/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MarketRouteImport } from './routes/market'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemesIndexRouteImport } from './routes/schemes.index'
import { Route as SchemesSlugRouteImport } from './routes/schemes.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedMandiPricesRouteImport } from './routes/_authenticated/mandi-prices'
import { Route as AuthenticatedLeafScanRouteImport } from './routes/_authenticated/leaf-scan'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCropAnalysisRouteImport } from './routes/_authenticated/crop-analysis'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIndexRoute = SchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesSlugRoute = SchemesSlugRouteImport.update({
  id: '/schemes/$slug',
  path: '/schemes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMandiPricesRoute =
  AuthenticatedMandiPricesRouteImport.update({
    id: '/mandi-prices',
    path: '/mandi-prices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeafScanRoute = AuthenticatedLeafScanRouteImport.update({
  id: '/leaf-scan',
  path: '/leaf-scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCropAnalysisRoute =
  AuthenticatedCropAnalysisRouteImport.update({
    id: '/crop-analysis',
    path: '/crop-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/market': typeof MarketRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/crop-analysis': typeof AuthenticatedCropAnalysisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaf-scan': typeof AuthenticatedLeafScanRoute
  '/mandi-prices': typeof AuthenticatedMandiPricesRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes/$slug': typeof SchemesSlugRoute
  '/schemes/': typeof SchemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/market': typeof MarketRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/crop-analysis': typeof AuthenticatedCropAnalysisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaf-scan': typeof AuthenticatedLeafScanRoute
  '/mandi-prices': typeof AuthenticatedMandiPricesRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes/$slug': typeof SchemesSlugRoute
  '/schemes': typeof SchemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/market': typeof MarketRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/crop-analysis': typeof AuthenticatedCropAnalysisRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaf-scan': typeof AuthenticatedLeafScanRoute
  '/_authenticated/mandi-prices': typeof AuthenticatedMandiPricesRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/schemes/$slug': typeof SchemesSlugRoute
  '/schemes/': typeof SchemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/market'
    | '/sitemap.xml'
    | '/crop-analysis'
    | '/dashboard'
    | '/leaf-scan'
    | '/mandi-prices'
    | '/marketplace'
    | '/onboarding'
    | '/profile'
    | '/schemes/$slug'
    | '/schemes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/market'
    | '/sitemap.xml'
    | '/crop-analysis'
    | '/dashboard'
    | '/leaf-scan'
    | '/mandi-prices'
    | '/marketplace'
    | '/onboarding'
    | '/profile'
    | '/schemes/$slug'
    | '/schemes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/market'
    | '/sitemap.xml'
    | '/_authenticated/crop-analysis'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaf-scan'
    | '/_authenticated/mandi-prices'
    | '/_authenticated/marketplace'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/schemes/$slug'
    | '/schemes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  MarketRoute: typeof MarketRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SchemesSlugRoute: typeof SchemesSlugRoute
  SchemesIndexRoute: typeof SchemesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/': {
      id: '/schemes/'
      path: '/schemes'
      fullPath: '/schemes/'
      preLoaderRoute: typeof SchemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$slug': {
      id: '/schemes/$slug'
      path: '/schemes/$slug'
      fullPath: '/schemes/$slug'
      preLoaderRoute: typeof SchemesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mandi-prices': {
      id: '/_authenticated/mandi-prices'
      path: '/mandi-prices'
      fullPath: '/mandi-prices'
      preLoaderRoute: typeof AuthenticatedMandiPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaf-scan': {
      id: '/_authenticated/leaf-scan'
      path: '/leaf-scan'
      fullPath: '/leaf-scan'
      preLoaderRoute: typeof AuthenticatedLeafScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crop-analysis': {
      id: '/_authenticated/crop-analysis'
      path: '/crop-analysis'
      fullPath: '/crop-analysis'
      preLoaderRoute: typeof AuthenticatedCropAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCropAnalysisRoute: typeof AuthenticatedCropAnalysisRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeafScanRoute: typeof AuthenticatedLeafScanRoute
  AuthenticatedMandiPricesRoute: typeof AuthenticatedMandiPricesRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCropAnalysisRoute: AuthenticatedCropAnalysisRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeafScanRoute: AuthenticatedLeafScanRoute,
  AuthenticatedMandiPricesRoute: AuthenticatedMandiPricesRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  MarketRoute: MarketRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SchemesSlugRoute: SchemesSlugRoute,
  SchemesIndexRoute: SchemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
